package sk.train.model;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.10
 * 2024-01-27T19:00:43.611+01:00
 * Generated source version: 3.4.10
 *
 */
@WebService(targetNamespace = "http://ws.train.sk/", name = "EmpServiceIf")
@XmlSeeAlso({ObjectFactory.class})
public interface EmpServiceIf {

    @WebMethod
    @RequestWrapper(localName = "deleteEmp", targetNamespace = "http://ws.train.sk/", className = "sk.train.model.DeleteEmp")
    @ResponseWrapper(localName = "deleteEmpResponse", targetNamespace = "http://ws.train.sk/", className = "sk.train.model.DeleteEmpResponse")
    public void deleteEmp(

        @WebParam(name = "arg0", targetNamespace = "")
        long arg0
    );

    @WebMethod
    @RequestWrapper(localName = "createEmp", targetNamespace = "http://ws.train.sk/", className = "sk.train.model.CreateEmp")
    @ResponseWrapper(localName = "createEmpResponse", targetNamespace = "http://ws.train.sk/", className = "sk.train.model.CreateEmpResponse")
    public void createEmp(

        @WebParam(name = "arg0", targetNamespace = "")
        sk.train.model.Employee arg0
    );

    @WebMethod
    @RequestWrapper(localName = "readEmp", targetNamespace = "http://ws.train.sk/", className = "sk.train.model.ReadEmp")
    @ResponseWrapper(localName = "readEmpResponse", targetNamespace = "http://ws.train.sk/", className = "sk.train.model.ReadEmpResponse")
    @WebResult(name = "return", targetNamespace = "")
    public sk.train.model.Employee readEmp(

        @WebParam(name = "arg0", targetNamespace = "")
        long arg0
    );

    @WebMethod
    @RequestWrapper(localName = "updateDep", targetNamespace = "http://ws.train.sk/", className = "sk.train.model.UpdateDep")
    @ResponseWrapper(localName = "updateDepResponse", targetNamespace = "http://ws.train.sk/", className = "sk.train.model.UpdateDepResponse")
    public void updateDep(

        @WebParam(name = "arg0", targetNamespace = "")
        sk.train.model.Department arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getAllDeps", targetNamespace = "http://ws.train.sk/", className = "sk.train.model.GetAllDeps")
    @ResponseWrapper(localName = "getAllDepsResponse", targetNamespace = "http://ws.train.sk/", className = "sk.train.model.GetAllDepsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<sk.train.model.Department> getAllDeps()
;

    @WebMethod
    @RequestWrapper(localName = "createDep", targetNamespace = "http://ws.train.sk/", className = "sk.train.model.CreateDep")
    @ResponseWrapper(localName = "createDepResponse", targetNamespace = "http://ws.train.sk/", className = "sk.train.model.CreateDepResponse")
    public void createDep(

        @WebParam(name = "arg0", targetNamespace = "")
        sk.train.model.Department arg0
    );

    @WebMethod
    @RequestWrapper(localName = "deleteDep", targetNamespace = "http://ws.train.sk/", className = "sk.train.model.DeleteDep")
    @ResponseWrapper(localName = "deleteDepResponse", targetNamespace = "http://ws.train.sk/", className = "sk.train.model.DeleteDepResponse")
    public void deleteDep(

        @WebParam(name = "arg0", targetNamespace = "")
        long arg0
    );

    @WebMethod
    @RequestWrapper(localName = "readDep", targetNamespace = "http://ws.train.sk/", className = "sk.train.model.ReadDep")
    @ResponseWrapper(localName = "readDepResponse", targetNamespace = "http://ws.train.sk/", className = "sk.train.model.ReadDepResponse")
    @WebResult(name = "return", targetNamespace = "")
    public sk.train.model.Department readDep(

        @WebParam(name = "arg0", targetNamespace = "")
        long arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getAllEmps", targetNamespace = "http://ws.train.sk/", className = "sk.train.model.GetAllEmps")
    @ResponseWrapper(localName = "getAllEmpsResponse", targetNamespace = "http://ws.train.sk/", className = "sk.train.model.GetAllEmpsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<sk.train.model.Employee> getAllEmps()
;

    @WebMethod
    @RequestWrapper(localName = "updateEmp", targetNamespace = "http://ws.train.sk/", className = "sk.train.model.UpdateEmp")
    @ResponseWrapper(localName = "updateEmpResponse", targetNamespace = "http://ws.train.sk/", className = "sk.train.model.UpdateEmpResponse")
    public void updateEmp(

        @WebParam(name = "arg0", targetNamespace = "")
        sk.train.model.Employee arg0
    );
}
