package ws.javacream.org.samples.order;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.0.4
 * 2024-11-19T15:48:06.757+01:00
 * Generated source version: 4.0.4
 *
 */
@WebService(targetNamespace = "http://org.javacream.ws/samples/order", name = "SimpleOrderWebService")
@XmlSeeAlso({org.javacream.order.ObjectFactory.class, ObjectFactory.class})
public interface SimpleOrderWebService {

    @WebMethod
    @Action(input = "http://org.javacream.ws/samples/order/SimpleOrderWebService/createOrderRequest", output = "http://org.javacream.ws/samples/order/SimpleOrderWebService/createOrderResponse")
    @RequestWrapper(localName = "createOrder", targetNamespace = "http://org.javacream.ws/samples/order", className = "ws.javacream.org.samples.order.CreateOrder")
    @ResponseWrapper(localName = "createOrderResponse", targetNamespace = "http://org.javacream.ws/samples/order", className = "ws.javacream.org.samples.order.CreateOrderResponse")
    @WebResult(name = "order", targetNamespace = "")
    public org.javacream.order.Order createOrder(

        @WebParam(name = "customerId", targetNamespace = "http://org.javacream.ws/samples/order")
        java.lang.String customerId,
        @WebParam(name = "category", targetNamespace = "http://org.javacream.ws/samples/order")
        java.lang.String category,
        @WebParam(name = "item", targetNamespace = "http://org.javacream.ws/samples/order")
        java.lang.String item,
        @WebParam(name = "amount", targetNamespace = "http://org.javacream.ws/samples/order")
        int amount
    );

    @WebMethod
    @Action(input = "http://org.javacream.ws/samples/order/SimpleOrderWebService/findOrderByIdRequest", output = "http://org.javacream.ws/samples/order/SimpleOrderWebService/findOrderByIdResponse")
    @RequestWrapper(localName = "findOrderById", targetNamespace = "http://org.javacream.ws/samples/order", className = "ws.javacream.org.samples.order.FindOrderById")
    @ResponseWrapper(localName = "findOrderByIdResponse", targetNamespace = "http://org.javacream.ws/samples/order", className = "ws.javacream.org.samples.order.FindOrderByIdResponse")
    @WebResult(name = "order", targetNamespace = "")
    public org.javacream.order.Order findOrderById(

        @WebParam(name = "orderId", targetNamespace = "")
        java.lang.String orderId
    );
}
