package sk.train;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 4.0.4
 * 2024-11-18T06:26:54.750+01:00
 * Generated source version: 4.0.4
 *
 */
@WebServiceClient(name = "ExceptionServiceService",
                  wsdlLocation = "http://localhost:8080/Exception_WS/ExceptionService?wsdl",
                  targetNamespace = "http://train.sk/")
public class ExceptionServiceService extends Service {

    public static final URL WSDL_LOCATION;

    public static final QName SERVICE = new QName("http://train.sk/", "ExceptionServiceService");
    public static final QName ExceptionServicePort = new QName("http://train.sk/", "ExceptionServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/Exception_WS/ExceptionService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ExceptionServiceService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/Exception_WS/ExceptionService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ExceptionServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ExceptionServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ExceptionServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ExceptionServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ExceptionServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ExceptionServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ExceptionService
     */
    @WebEndpoint(name = "ExceptionServicePort")
    public ExceptionService getExceptionServicePort() {
        return super.getPort(ExceptionServicePort, ExceptionService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ExceptionService
     */
    @WebEndpoint(name = "ExceptionServicePort")
    public ExceptionService getExceptionServicePort(WebServiceFeature... features) {
        return super.getPort(ExceptionServicePort, ExceptionService.class, features);
    }

}
