
package sk.train;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.0.4
 * 2024-11-18T06:26:54.720+01:00
 * Generated source version: 4.0.4
 */

@WebFault(name = "IOException", targetNamespace = "http://train.sk/")
public class IOException_Exception extends Exception {

    private sk.train.IOException faultInfo;

    public IOException_Exception() {
        super();
    }

    public IOException_Exception(String message) {
        super(message);
    }

    public IOException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public IOException_Exception(String message, sk.train.IOException ioException) {
        super(message);
        this.faultInfo = ioException;
    }

    public IOException_Exception(String message, sk.train.IOException ioException, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = ioException;
    }

    public sk.train.IOException getFaultInfo() {
        return this.faultInfo;
    }
}
