
package sk.train;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.0.4
 * 2024-11-18T06:26:54.627+01:00
 * Generated source version: 4.0.4
 */

@WebFault(name = "KarrerException1", targetNamespace = "http://train.sk/")
public class KarrerException1_Exception extends Exception {

    private sk.train.KarrerException1 faultInfo;

    public KarrerException1_Exception() {
        super();
    }

    public KarrerException1_Exception(String message) {
        super(message);
    }

    public KarrerException1_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public KarrerException1_Exception(String message, sk.train.KarrerException1 karrerException1) {
        super(message);
        this.faultInfo = karrerException1;
    }

    public KarrerException1_Exception(String message, sk.train.KarrerException1 karrerException1, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = karrerException1;
    }

    public sk.train.KarrerException1 getFaultInfo() {
        return this.faultInfo;
    }
}
